package com.alone.mymall.mgb.model;

import java.io.Serializable;
import java.util.Date;

public class CmsSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.title
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.pic
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.product_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.recommend_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.create_time
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.collect_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer collectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.read_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.comment_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.album_pics
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.description
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.show_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer showStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.forward_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private Integer forwardCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_name
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.content
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.id
     *
     * @return the value of cms_subject.id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.id
     *
     * @param id the value for cms_subject.id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.category_id
     *
     * @return the value of cms_subject.category_id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.category_id
     *
     * @param categoryId the value for cms_subject.category_id
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.title
     *
     * @return the value of cms_subject.title
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.title
     *
     * @param title the value for cms_subject.title
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.pic
     *
     * @return the value of cms_subject.pic
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.pic
     *
     * @param pic the value for cms_subject.pic
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.product_count
     *
     * @return the value of cms_subject.product_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.product_count
     *
     * @param productCount the value for cms_subject.product_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.recommend_status
     *
     * @return the value of cms_subject.recommend_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.recommend_status
     *
     * @param recommendStatus the value for cms_subject.recommend_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.create_time
     *
     * @return the value of cms_subject.create_time
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.create_time
     *
     * @param createTime the value for cms_subject.create_time
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.collect_count
     *
     * @return the value of cms_subject.collect_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.collect_count
     *
     * @param collectCount the value for cms_subject.collect_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.read_count
     *
     * @return the value of cms_subject.read_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.read_count
     *
     * @param readCount the value for cms_subject.read_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.comment_count
     *
     * @return the value of cms_subject.comment_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.comment_count
     *
     * @param commentCount the value for cms_subject.comment_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.album_pics
     *
     * @return the value of cms_subject.album_pics
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getAlbumPics() {
        return albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.album_pics
     *
     * @param albumPics the value for cms_subject.album_pics
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setAlbumPics(String albumPics) {
        this.albumPics = albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.description
     *
     * @return the value of cms_subject.description
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.description
     *
     * @param description the value for cms_subject.description
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.show_status
     *
     * @return the value of cms_subject.show_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.show_status
     *
     * @param showStatus the value for cms_subject.show_status
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.forward_count
     *
     * @return the value of cms_subject.forward_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public Integer getForwardCount() {
        return forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.forward_count
     *
     * @param forwardCount the value for cms_subject.forward_count
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setForwardCount(Integer forwardCount) {
        this.forwardCount = forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.category_name
     *
     * @return the value of cms_subject.category_name
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.category_name
     *
     * @param categoryName the value for cms_subject.category_name
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.content
     *
     * @return the value of cms_subject.content
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.content
     *
     * @param content the value for cms_subject.content
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", title=").append(title);
        sb.append(", pic=").append(pic);
        sb.append(", productCount=").append(productCount);
        sb.append(", recommendStatus=").append(recommendStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", collectCount=").append(collectCount);
        sb.append(", readCount=").append(readCount);
        sb.append(", commentCount=").append(commentCount);
        sb.append(", albumPics=").append(albumPics);
        sb.append(", description=").append(description);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", forwardCount=").append(forwardCount);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}