package com.alone.mymall.mgb.model;

import java.io.Serializable;

public class CmsSubjectProductRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.subject_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject_product_relation.product_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_subject_product_relation
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.id
     *
     * @return the value of cms_subject_product_relation.id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.id
     *
     * @param id the value for cms_subject_product_relation.id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.subject_id
     *
     * @return the value of cms_subject_product_relation.subject_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.subject_id
     *
     * @param subjectId the value for cms_subject_product_relation.subject_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject_product_relation.product_id
     *
     * @return the value of cms_subject_product_relation.product_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject_product_relation.product_id
     *
     * @param productId the value for cms_subject_product_relation.product_id
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject_product_relation
     *
     * @mbggenerated Fri Dec 20 11:49:27 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}