package com.alone.mymall.mgb.model;

import java.io.Serializable;
import java.util.Date;

public class OmsOrderOperateHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.order_id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.operate_man
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private String operateMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.create_time
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.order_status
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_operate_history.note
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order_operate_history
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.id
     *
     * @return the value of oms_order_operate_history.id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.id
     *
     * @param id the value for oms_order_operate_history.id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.order_id
     *
     * @return the value of oms_order_operate_history.order_id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.order_id
     *
     * @param orderId the value for oms_order_operate_history.order_id
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.operate_man
     *
     * @return the value of oms_order_operate_history.operate_man
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public String getOperateMan() {
        return operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.operate_man
     *
     * @param operateMan the value for oms_order_operate_history.operate_man
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setOperateMan(String operateMan) {
        this.operateMan = operateMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.create_time
     *
     * @return the value of oms_order_operate_history.create_time
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.create_time
     *
     * @param createTime the value for oms_order_operate_history.create_time
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.order_status
     *
     * @return the value of oms_order_operate_history.order_status
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.order_status
     *
     * @param orderStatus the value for oms_order_operate_history.order_status
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_operate_history.note
     *
     * @return the value of oms_order_operate_history.note
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_operate_history.note
     *
     * @param note the value for oms_order_operate_history.note
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_operate_history
     *
     * @mbggenerated Wed Dec 18 21:31:57 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", operateMan=").append(operateMan);
        sb.append(", createTime=").append(createTime);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}