package com.alone.mymall.mgb.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.create_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.member_username
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String memberUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.total_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.freight_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal freightAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal promotionAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal integrationAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.coupon_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal couponAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.discount_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.pay_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.source_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.order_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_company
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String deliverySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.auto_confirm_day
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer autoConfirmDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer integration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.growth
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer growth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.promotion_info
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String promotionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer billType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_header
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String billHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_content
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String billContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String billReceiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.bill_receiver_email
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String billReceiverEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_name
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_post_code
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_province
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_city
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_region
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receiver_detail_address
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String receiverDetailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.note
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.confirm_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer confirmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delete_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.use_integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Integer useIntegration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.payment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.delivery_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.receive_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date receiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.comment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.modify_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.id
     *
     * @return the value of oms_order.id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.id
     *
     * @param id the value for oms_order.id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.member_id
     *
     * @return the value of oms_order.member_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.member_id
     *
     * @param memberId the value for oms_order.member_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.coupon_id
     *
     * @return the value of oms_order.coupon_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.coupon_id
     *
     * @param couponId the value for oms_order.coupon_id
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_sn
     *
     * @return the value of oms_order.order_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_sn
     *
     * @param orderSn the value for oms_order.order_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.create_time
     *
     * @return the value of oms_order.create_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.create_time
     *
     * @param createTime the value for oms_order.create_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.member_username
     *
     * @return the value of oms_order.member_username
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getMemberUsername() {
        return memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.member_username
     *
     * @param memberUsername the value for oms_order.member_username
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setMemberUsername(String memberUsername) {
        this.memberUsername = memberUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.total_amount
     *
     * @return the value of oms_order.total_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.total_amount
     *
     * @param totalAmount the value for oms_order.total_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_amount
     *
     * @return the value of oms_order.pay_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_amount
     *
     * @param payAmount the value for oms_order.pay_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.freight_amount
     *
     * @return the value of oms_order.freight_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getFreightAmount() {
        return freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.freight_amount
     *
     * @param freightAmount the value for oms_order.freight_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setFreightAmount(BigDecimal freightAmount) {
        this.freightAmount = freightAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.promotion_amount
     *
     * @return the value of oms_order.promotion_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getPromotionAmount() {
        return promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.promotion_amount
     *
     * @param promotionAmount the value for oms_order.promotion_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setPromotionAmount(BigDecimal promotionAmount) {
        this.promotionAmount = promotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.integration_amount
     *
     * @return the value of oms_order.integration_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getIntegrationAmount() {
        return integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.integration_amount
     *
     * @param integrationAmount the value for oms_order.integration_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setIntegrationAmount(BigDecimal integrationAmount) {
        this.integrationAmount = integrationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.coupon_amount
     *
     * @return the value of oms_order.coupon_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.coupon_amount
     *
     * @param couponAmount the value for oms_order.coupon_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.discount_amount
     *
     * @return the value of oms_order.discount_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.discount_amount
     *
     * @param discountAmount the value for oms_order.discount_amount
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.pay_type
     *
     * @return the value of oms_order.pay_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.pay_type
     *
     * @param payType the value for oms_order.pay_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.source_type
     *
     * @return the value of oms_order.source_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.source_type
     *
     * @param sourceType the value for oms_order.source_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.status
     *
     * @return the value of oms_order.status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.status
     *
     * @param status the value for oms_order.status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.order_type
     *
     * @return the value of oms_order.order_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.order_type
     *
     * @param orderType the value for oms_order.order_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_company
     *
     * @return the value of oms_order.delivery_company
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_company
     *
     * @param deliveryCompany the value for oms_order.delivery_company
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_sn
     *
     * @return the value of oms_order.delivery_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getDeliverySn() {
        return deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_sn
     *
     * @param deliverySn the value for oms_order.delivery_sn
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setDeliverySn(String deliverySn) {
        this.deliverySn = deliverySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.auto_confirm_day
     *
     * @return the value of oms_order.auto_confirm_day
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getAutoConfirmDay() {
        return autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.auto_confirm_day
     *
     * @param autoConfirmDay the value for oms_order.auto_confirm_day
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setAutoConfirmDay(Integer autoConfirmDay) {
        this.autoConfirmDay = autoConfirmDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.integration
     *
     * @return the value of oms_order.integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.integration
     *
     * @param integration the value for oms_order.integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setIntegration(Integer integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.growth
     *
     * @return the value of oms_order.growth
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getGrowth() {
        return growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.growth
     *
     * @param growth the value for oms_order.growth
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setGrowth(Integer growth) {
        this.growth = growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.promotion_info
     *
     * @return the value of oms_order.promotion_info
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getPromotionInfo() {
        return promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.promotion_info
     *
     * @param promotionInfo the value for oms_order.promotion_info
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setPromotionInfo(String promotionInfo) {
        this.promotionInfo = promotionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_type
     *
     * @return the value of oms_order.bill_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_type
     *
     * @param billType the value for oms_order.bill_type
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_header
     *
     * @return the value of oms_order.bill_header
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getBillHeader() {
        return billHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_header
     *
     * @param billHeader the value for oms_order.bill_header
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setBillHeader(String billHeader) {
        this.billHeader = billHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_content
     *
     * @return the value of oms_order.bill_content
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getBillContent() {
        return billContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_content
     *
     * @param billContent the value for oms_order.bill_content
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setBillContent(String billContent) {
        this.billContent = billContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_receiver_phone
     *
     * @return the value of oms_order.bill_receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getBillReceiverPhone() {
        return billReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_receiver_phone
     *
     * @param billReceiverPhone the value for oms_order.bill_receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setBillReceiverPhone(String billReceiverPhone) {
        this.billReceiverPhone = billReceiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.bill_receiver_email
     *
     * @return the value of oms_order.bill_receiver_email
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getBillReceiverEmail() {
        return billReceiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.bill_receiver_email
     *
     * @param billReceiverEmail the value for oms_order.bill_receiver_email
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setBillReceiverEmail(String billReceiverEmail) {
        this.billReceiverEmail = billReceiverEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_name
     *
     * @return the value of oms_order.receiver_name
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_name
     *
     * @param receiverName the value for oms_order.receiver_name
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_phone
     *
     * @return the value of oms_order.receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_phone
     *
     * @param receiverPhone the value for oms_order.receiver_phone
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_post_code
     *
     * @return the value of oms_order.receiver_post_code
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverPostCode() {
        return receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_post_code
     *
     * @param receiverPostCode the value for oms_order.receiver_post_code
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverPostCode(String receiverPostCode) {
        this.receiverPostCode = receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_province
     *
     * @return the value of oms_order.receiver_province
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_province
     *
     * @param receiverProvince the value for oms_order.receiver_province
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_city
     *
     * @return the value of oms_order.receiver_city
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_city
     *
     * @param receiverCity the value for oms_order.receiver_city
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_region
     *
     * @return the value of oms_order.receiver_region
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverRegion() {
        return receiverRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_region
     *
     * @param receiverRegion the value for oms_order.receiver_region
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverRegion(String receiverRegion) {
        this.receiverRegion = receiverRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receiver_detail_address
     *
     * @return the value of oms_order.receiver_detail_address
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getReceiverDetailAddress() {
        return receiverDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receiver_detail_address
     *
     * @param receiverDetailAddress the value for oms_order.receiver_detail_address
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiverDetailAddress(String receiverDetailAddress) {
        this.receiverDetailAddress = receiverDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.note
     *
     * @return the value of oms_order.note
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.note
     *
     * @param note the value for oms_order.note
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.confirm_status
     *
     * @return the value of oms_order.confirm_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getConfirmStatus() {
        return confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.confirm_status
     *
     * @param confirmStatus the value for oms_order.confirm_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setConfirmStatus(Integer confirmStatus) {
        this.confirmStatus = confirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delete_status
     *
     * @return the value of oms_order.delete_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delete_status
     *
     * @param deleteStatus the value for oms_order.delete_status
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.use_integration
     *
     * @return the value of oms_order.use_integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Integer getUseIntegration() {
        return useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.use_integration
     *
     * @param useIntegration the value for oms_order.use_integration
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setUseIntegration(Integer useIntegration) {
        this.useIntegration = useIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.payment_time
     *
     * @return the value of oms_order.payment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.payment_time
     *
     * @param paymentTime the value for oms_order.payment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.delivery_time
     *
     * @return the value of oms_order.delivery_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.delivery_time
     *
     * @param deliveryTime the value for oms_order.delivery_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.receive_time
     *
     * @return the value of oms_order.receive_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.receive_time
     *
     * @param receiveTime the value for oms_order.receive_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.comment_time
     *
     * @return the value of oms_order.comment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.comment_time
     *
     * @param commentTime the value for oms_order.comment_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.modify_time
     *
     * @return the value of oms_order.modify_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.modify_time
     *
     * @param modifyTime the value for oms_order.modify_time
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbggenerated Wed Dec 18 21:18:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", couponId=").append(couponId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", memberUsername=").append(memberUsername);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", freightAmount=").append(freightAmount);
        sb.append(", promotionAmount=").append(promotionAmount);
        sb.append(", integrationAmount=").append(integrationAmount);
        sb.append(", couponAmount=").append(couponAmount);
        sb.append(", discountAmount=").append(discountAmount);
        sb.append(", payType=").append(payType);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", status=").append(status);
        sb.append(", orderType=").append(orderType);
        sb.append(", deliveryCompany=").append(deliveryCompany);
        sb.append(", deliverySn=").append(deliverySn);
        sb.append(", autoConfirmDay=").append(autoConfirmDay);
        sb.append(", integration=").append(integration);
        sb.append(", growth=").append(growth);
        sb.append(", promotionInfo=").append(promotionInfo);
        sb.append(", billType=").append(billType);
        sb.append(", billHeader=").append(billHeader);
        sb.append(", billContent=").append(billContent);
        sb.append(", billReceiverPhone=").append(billReceiverPhone);
        sb.append(", billReceiverEmail=").append(billReceiverEmail);
        sb.append(", receiverName=").append(receiverName);
        sb.append(", receiverPhone=").append(receiverPhone);
        sb.append(", receiverPostCode=").append(receiverPostCode);
        sb.append(", receiverProvince=").append(receiverProvince);
        sb.append(", receiverCity=").append(receiverCity);
        sb.append(", receiverRegion=").append(receiverRegion);
        sb.append(", receiverDetailAddress=").append(receiverDetailAddress);
        sb.append(", note=").append(note);
        sb.append(", confirmStatus=").append(confirmStatus);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", useIntegration=").append(useIntegration);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}