package com.alone.mymall.mgb.model;

import java.io.Serializable;

public class OmsOrderSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.id
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.flash_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Integer flashOrderOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.normal_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Integer normalOrderOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.confirm_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Integer confirmOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.finish_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Integer finishOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_setting.comment_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private Integer commentOvertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order_setting
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.id
     *
     * @return the value of oms_order_setting.id
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.id
     *
     * @param id the value for oms_order_setting.id
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.flash_order_overtime
     *
     * @return the value of oms_order_setting.flash_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Integer getFlashOrderOvertime() {
        return flashOrderOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.flash_order_overtime
     *
     * @param flashOrderOvertime the value for oms_order_setting.flash_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setFlashOrderOvertime(Integer flashOrderOvertime) {
        this.flashOrderOvertime = flashOrderOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.normal_order_overtime
     *
     * @return the value of oms_order_setting.normal_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Integer getNormalOrderOvertime() {
        return normalOrderOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.normal_order_overtime
     *
     * @param normalOrderOvertime the value for oms_order_setting.normal_order_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setNormalOrderOvertime(Integer normalOrderOvertime) {
        this.normalOrderOvertime = normalOrderOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.confirm_overtime
     *
     * @return the value of oms_order_setting.confirm_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Integer getConfirmOvertime() {
        return confirmOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.confirm_overtime
     *
     * @param confirmOvertime the value for oms_order_setting.confirm_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setConfirmOvertime(Integer confirmOvertime) {
        this.confirmOvertime = confirmOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.finish_overtime
     *
     * @return the value of oms_order_setting.finish_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Integer getFinishOvertime() {
        return finishOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.finish_overtime
     *
     * @param finishOvertime the value for oms_order_setting.finish_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setFinishOvertime(Integer finishOvertime) {
        this.finishOvertime = finishOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_setting.comment_overtime
     *
     * @return the value of oms_order_setting.comment_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public Integer getCommentOvertime() {
        return commentOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_setting.comment_overtime
     *
     * @param commentOvertime the value for oms_order_setting.comment_overtime
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    public void setCommentOvertime(Integer commentOvertime) {
        this.commentOvertime = commentOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_setting
     *
     * @mbggenerated Wed Dec 18 21:36:57 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flashOrderOvertime=").append(flashOrderOvertime);
        sb.append(", normalOrderOvertime=").append(normalOrderOvertime);
        sb.append(", confirmOvertime=").append(confirmOvertime);
        sb.append(", finishOvertime=").append(finishOvertime);
        sb.append(", commentOvertime=").append(commentOvertime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}