package com.alone.mymall.mgb.model;

import java.io.Serializable;
import java.util.Date;

public class UmsAdminLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.admin_id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.create_time
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.ip
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.address
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.user_agent
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.id
     *
     * @return the value of ums_admin_login_log.id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.id
     *
     * @param id the value for ums_admin_login_log.id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.admin_id
     *
     * @return the value of ums_admin_login_log.admin_id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.admin_id
     *
     * @param adminId the value for ums_admin_login_log.admin_id
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.create_time
     *
     * @return the value of ums_admin_login_log.create_time
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.create_time
     *
     * @param createTime the value for ums_admin_login_log.create_time
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.ip
     *
     * @return the value of ums_admin_login_log.ip
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.ip
     *
     * @param ip the value for ums_admin_login_log.ip
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.address
     *
     * @return the value of ums_admin_login_log.address
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.address
     *
     * @param address the value for ums_admin_login_log.address
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.user_agent
     *
     * @return the value of ums_admin_login_log.user_agent
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.user_agent
     *
     * @param userAgent the value for ums_admin_login_log.user_agent
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adminId=").append(adminId);
        sb.append(", createTime=").append(createTime);
        sb.append(", ip=").append(ip);
        sb.append(", address=").append(address);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}