package com.alone.mymall.mgb.model;

import java.io.Serializable;

public class UmsAdminRoleRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.admin_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.role_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_admin_role_relation
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.id
     *
     * @return the value of ums_admin_role_relation.id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.id
     *
     * @param id the value for ums_admin_role_relation.id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.admin_id
     *
     * @return the value of ums_admin_role_relation.admin_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.admin_id
     *
     * @param adminId the value for ums_admin_role_relation.admin_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.role_id
     *
     * @return the value of ums_admin_role_relation.role_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.role_id
     *
     * @param roleId the value for ums_admin_role_relation.role_id
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_role_relation
     *
     * @mbggenerated Fri Dec 06 15:20:26 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adminId=").append(adminId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}