package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.CmsSubject;
import com.alone.mymall.mgb.model.CmsSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int countByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int deleteByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int insert(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int insertSelective(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    List<CmsSubject> selectByExampleWithBLOBs(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    List<CmsSubject> selectByExample(CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    CmsSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByExample(@Param("record") CmsSubject record, @Param("example") CmsSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByPrimaryKeySelective(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CmsSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subject
     *
     * @mbggenerated Fri Dec 20 11:56:48 CST 2019
     */
    int updateByPrimaryKey(CmsSubject record);
}