package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.OmsOrderReturnApply;
import com.alone.mymall.mgb.model.OmsOrderReturnApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderReturnApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int countByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int deleteByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int insert(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int insertSelective(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    List<OmsOrderReturnApply> selectByExample(OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    OmsOrderReturnApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") OmsOrderReturnApply record, @Param("example") OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int updateByExample(@Param("record") OmsOrderReturnApply record, @Param("example") OmsOrderReturnApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int updateByPrimaryKeySelective(OmsOrderReturnApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbggenerated Wed Dec 18 21:26:17 CST 2019
     */
    int updateByPrimaryKey(OmsOrderReturnApply record);
}