package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.PmsProductVerifyRecord;
import com.alone.mymall.mgb.model.PmsProductVerifyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductVerifyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int countByExample(PmsProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int deleteByExample(PmsProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int insert(PmsProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int insertSelective(PmsProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    List<PmsProductVerifyRecord> selectByExample(PmsProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    PmsProductVerifyRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") PmsProductVerifyRecord record, @Param("example") PmsProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int updateByExample(@Param("record") PmsProductVerifyRecord record, @Param("example") PmsProductVerifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int updateByPrimaryKeySelective(PmsProductVerifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_verify_record
     *
     * @mbggenerated Mon Nov 25 10:37:45 CST 2019
     */
    int updateByPrimaryKey(PmsProductVerifyRecord record);
}