package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.SmsHomeNewProduct;
import com.alone.mymall.mgb.model.SmsHomeNewProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeNewProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int countByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int deleteByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int insert(SmsHomeNewProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int insertSelective(SmsHomeNewProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    List<SmsHomeNewProduct> selectByExample(SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    SmsHomeNewProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsHomeNewProduct record, @Param("example") SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int updateByExample(@Param("record") SmsHomeNewProduct record, @Param("example") SmsHomeNewProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int updateByPrimaryKeySelective(SmsHomeNewProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbggenerated Tue Dec 17 10:28:51 CST 2019
     */
    int updateByPrimaryKey(SmsHomeNewProduct record);
}