package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.SmsHomeBrand;
import com.alone.mymall.mgb.model.SmsHomeBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsHomeBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int countByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int deleteByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int insert(SmsHomeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int insertSelective(SmsHomeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    List<SmsHomeBrand> selectByExample(SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    SmsHomeBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsHomeBrand record, @Param("example") SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int updateByExample(@Param("record") SmsHomeBrand record, @Param("example") SmsHomeBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int updateByPrimaryKeySelective(SmsHomeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_brand
     *
     * @mbggenerated Tue Dec 17 10:25:58 CST 2019
     */
    int updateByPrimaryKey(SmsHomeBrand record);
}