package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.UmsAdminLoginLog;
import com.alone.mymall.mgb.model.UmsAdminLoginLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UmsAdminLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int countByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int deleteByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int insert(UmsAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int insertSelective(UmsAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    List<UmsAdminLoginLog> selectByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    UmsAdminLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") UmsAdminLoginLog record, @Param("example") UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int updateByExample(@Param("record") UmsAdminLoginLog record, @Param("example") UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int updateByPrimaryKeySelective(UmsAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbggenerated Fri Dec 06 13:34:11 CST 2019
     */
    int updateByPrimaryKey(UmsAdminLoginLog record);
}