package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.UmsAdminPermissionRelation;
import com.alone.mymall.mgb.model.UmsAdminPermissionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsAdminPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int countByExample(UmsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int deleteByExample(UmsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int insert(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int insertSelective(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    List<UmsAdminPermissionRelation> selectByExample(UmsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    UmsAdminPermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") UmsAdminPermissionRelation record, @Param("example") UmsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int updateByExample(@Param("record") UmsAdminPermissionRelation record, @Param("example") UmsAdminPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int updateByPrimaryKeySelective(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbggenerated Sat Dec 07 13:31:27 CST 2019
     */
    int updateByPrimaryKey(UmsAdminPermissionRelation record);
}