package com.alone.mymall.mgb.mapper;

import com.alone.mymall.mgb.model.UmsMemberLevel;
import com.alone.mymall.mgb.model.UmsMemberLevelExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UmsMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int countByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int deleteByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int insert(UmsMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int insertSelective(UmsMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    List<UmsMemberLevel> selectByExample(UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    UmsMemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") UmsMemberLevel record, @Param("example") UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int updateByExample(@Param("record") UmsMemberLevel record, @Param("example") UmsMemberLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int updateByPrimaryKeySelective(UmsMemberLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbggenerated Sun Dec 08 20:14:36 CST 2019
     */
    int updateByPrimaryKey(UmsMemberLevel record);
}